Windows: Add universal support for Microsoft Windows (#166)
This PR adds support for the following Microsoft Windows versions:

* Windows Server 2022
* Windows Server 2019
* Windows Server 2016
* Windows 10 Pro 22H2

Support for Windows 11 is in the works and will be added subsequently.

Please kindly review & test and let me know if you encounter any issues.
Please consult the README.md file for details.

Thank you,
Alan

Closes: #3

---------

Co-authored-by: Gabriel Ramirez <gabrielramirez1109@gmail.com>

diff --git a/windows/curtin/finalize b/windows/curtin/finalize
--- a/windows/curtin/finalize
+++ b/windows/curtin/finalize
@@ -1,11 +1,26 @@
 #!/bin/bash
 
-export PYTHONPATH='/curtin'
+PYTHON2=`/bin/which python`
+PYTHON3=`/bin/which python3`
 
-# Ubuntu 16.04 only ships with Python 3 while previous versions only ship
-# with Python 2.
-if type -p python > /dev/null; then
-    exec python "$0.py" "$@"
-else
-    exec python3 "$0.py" "$@"
+PYTHON=${PYTHON2:-$PYTHON3}
+
+if [ -z $PYTHON ]
+then
+    echo "Failed to find python interpretor"
+    exit 1
 fi
+
+SCRIPT_DIR=`/usr/bin/dirname $0`
+ABSPATH=`/bin/readlink -m $SCRIPT_DIR`
+
+FINALIZE="$ABSPATH/finalize.py"
+
+if [ ! -e $FINALIZE ]
+then
+    echo "No finalize script available"
+    exit 0
+fi
+
+$PYTHON $FINALIZE
+
